/**
 * Renders the arrival workspace and writes the shipped asset.
 *
 *   node design/render/capture.mjs [origin]
 *
 * Drives `/render-studio` in a headless browser, waits for the scene to report
 * ready, grabs the canvas at full 3840x2400, and writes:
 *
 *   public/arrival/workspace.png        the render, downsampled 2x
 *   public/arrival/workspace.json       the projected screen quad, 0..1
 *
 * The JSON is the important half. It is the primary monitor's screen corners
 * as the CAMERA saw them, so the runtime maps a live DOM surface onto exactly
 * that quad instead of anyone eyeballing pixel coordinates against a picture.
 * Move the monitor in the scene, re-run this, and the site follows.
 *
 * Downsampling 2x is free supersampling — it is the cheapest antialiasing
 * available and the single biggest quality difference between this and a
 * real-time render.
 */

import { chromium } from "playwright";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ORIGIN = process.argv[2] ?? "http://localhost:6200";
const OUT_DIR = join(process.cwd(), "public", "arrival");

const browser = await chromium.launch({
  channel: "chrome",
  args: ["--use-gl=angle", "--enable-unsafe-swiftshader", "--disable-lcd-text"],
});

// Deliberately a small viewport: the canvas renders at its own backing size
// regardless, and a huge viewport only costs compositing.
const page = await browser.newPage({ viewport: { width: 1200, height: 800 } });

const errors = [];
page.on("pageerror", (e) => errors.push(e.message.slice(0, 200)));
page.on("console", (m) => {
  if (m.type() === "error") errors.push("console: " + m.text().slice(0, 200));
});

console.log("→ loading", ORIGIN + "/render-studio");
await page.goto(ORIGIN + "/render-studio", { waitUntil: "domcontentloaded" });

await page.waitForSelector("html[data-render-ready]", { timeout: 90_000 });
await page.waitForTimeout(1200);

if (errors.length) {
  console.error("✗ scene reported errors:\n  " + errors.join("\n  "));
  await browser.close();
  process.exit(1);
}

// Pull the full-resolution pixels straight off the canvas rather than
// screenshotting the element, which would capture it at its CSS size.
const { dataUrl, corners } = await page.evaluate(() => {
  const c = document.querySelector("[data-render-canvas]");
  const holder = document.querySelector("[data-screen-corners]");
  return {
    dataUrl: c.toDataURL("image/png"),
    corners: holder?.getAttribute("data-screen-corners") ?? "[]",
  };
});

mkdirSync(OUT_DIR, { recursive: true });

const raw = Buffer.from(dataUrl.split(",")[1], "base64");
writeFileSync(join(OUT_DIR, "workspace-4k.png"), raw);

const quad = JSON.parse(corners);
writeFileSync(
  join(OUT_DIR, "workspace.json"),
  JSON.stringify(
    {
      note:
        "Primary monitor screen corners as projected by the render camera, " +
        "in 0..1 image space, order TL TR BR BL. Generated by " +
        "design/render/capture.mjs — do not hand-edit.",
      renderWidth: 3840,
      renderHeight: 2400,
      screenQuad: quad,
    },
    null,
    2,
  ),
);

console.log("✓ wrote public/arrival/workspace-4k.png", (raw.length / 1024 / 1024).toFixed(2) + "MB");
console.log("✓ wrote public/arrival/workspace.json");
console.log("  screen quad:", JSON.stringify(quad));

await browser.close();
